-- Create the Channel records --
INSERT INTO channel(name, yt_channel_id)
VALUES 
	('videogamedunkey', 'UCsvn_Po0SmunchJYOWpOxMg'),
	('WaLter .NO (coming soon)', 'UCbOPMX9iWXlulmbNXrz6oLw'),
	('Dunk Tank (coming soon)', 'UCGiJeCKTVKIxtaYZOidh19g'),
	('Leahbee (coming soon)', 'UCq7D2jqBfjse5M18CaLlTjA');

-- Create the CaptionType records --
INSERT INTO caption_type(name)
VALUES 
	('English (auto-generated)'),
	('English');

-- Unsupported Videos (as of 6/21/2022)
INSERT INTO unsupported_video(yt_video_id, title, reason)
VALUES
	('Wqsb7VR6EB8', 'LoL : Ashe''s Revenge', 'Music only'),
	('8MhOouhhrTU', 'Black Ops : Epic Boner Jamz', 'Music only'),
	('uZfJ5S3WCY4', 'Modern Trollfare', 'No captions'),
	('o7HUbFZW_kU', 'League of Legends : AFK Troller Strategy', 'Music only'),
	('3S8BvTbhkY0', 'Crysis 2 - Console Version (dunkview)', 'No captions'),
	('RM9R4IFSMHQ', 'Falcom Chip !', 'No captions'),
	('-uo-JnbtVqo', 'League of Legends : Epic Escape', 'Music only'),
	('yQKI9oclZsk', 'League of Legends : OOO MAMA', 'No captions'),
	('Ong43KWh_x8', 'League of Legends : Ranked', 'Music only'),
	('gDHMtw_ECjE', 'League of Legends : Dream Team', 'No captions'),
	('8qnQNe9zQmo', 'Skyman and the Boosher Mover', 'No captions'),
	('wWBYZQwmJCg', 'Beast Mode Counter Strike Pwn Town', 'Music only'),
	('zIoJndp0sKI', 'League of Legends : Renekton''s Alt. Lore', 'No captions'),
	('kvwmNx5AeAs', 'League of Legends : Weo Weo Weo', 'Just noises'),
	('PIJ54HCj_mY', 'LoL Cypher - Dunkey (calling out Protoman)', 'No captions'),
	('Mj5KiiHznJk', 'League of Legends : Wondershot Ashe', 'Music only'),
	('7pOAsXK3bYs', 'League of Legends : Five Man Jungle', 'No captions'),
	('YB_-T_dW2Aw', 'League of Legends : Foxstar 4D', 'No captions'),
	('JUFl_sDOHlM', 'League of Legends : Shoot Boys', 'No captions'),
	('zPej5c7DU7Q', 'League of Legends : Fizz Glitch', 'No captions'),
	('2YeTbQYF6Hk', 'League of Legends : Varus is Out', 'No captions'),
	('aYDIYzPFvKc', 'Diablo 3 : Inside Look', 'No captions'),
	('LmjHx7yIvV8', 'League of Legends : Meet the Sin', 'No captions'),
	('VS9IhcD1YYE', 'League of Legends : Downright Dyruis', 'No captions'),
	('17XvXLHFDP0', 'League of Legends : Impressions', 'No captions'),
	('6r5sMN_QGQs', 'Dark Knight Rises is Sold Out', 'No captions'),
	('w5_cVzKFyTk', 'League of Legends : Weo Weo Caitlyn', 'No captions'),
	('Jkg8GiriHvU', 'League of Legends : Riot Points Hack Get 60k RP', 'No captions'),
	('iUejvXJ9-II', 'League of Legends : The Movie', 'No captions'),
	('rw2sMk-PTp8', 'Super Mario 64 (Ep. 18) : The Return', 'No captions'),
	('M_avgJJvgSc', 'League of Legends : The Lion Book', 'No captions'),
	('qdroeDSpoGU', 'League of Legends : Team All Mid', 'No captions'),
	('WEtf3XolX9w', 'League of Legends : Slam House', 'No captions'),
	('rCsvWfEMcII', 'League of Legends : Swat Recon', 'No captions'),
	('ECQKwvEoD8o', 'Phone Men', 'No captions'),
	('c79sW3gVp8s', 'League of Legends : Gentlemen''s Tribunal', 'No captions'),
	('t88VU72eAI0', 'League of Legends : New Rengar Build', 'No captions'),
	('bxKSMQ7upHg', 'Super Mario 64 (Ep. 19) : Wiggler''s Red Coins', 'No captions'),
	('GGEGF7cHmMU', 'Harlem Shake', 'Music only'),
	('kacTMmoQPQM', 'Dunkey Die', 'Music only'),
	('kdGyUvCksD8', 'League of Legends : Bird Bitch', 'No captions'),
	('sdnYy1b8KEY', 'League of Legends : Die Sounds', 'Just noises'),
	('kCHVdq73o4s', 'League of Legends : Dubstep Singed', 'No captions'),
	('EC-VrN9ABkk', 'League of Legends : Beo Beo Trungle', 'No captions'),
	('4O4SRcNBGp8', 'League of Legends : Jinx', 'Just noises'),
	('AaxobrC3Qmo', 'League of Legends : Hell Jam', 'No captions'),
	('PttKq0GcnoQ', 'Soccer', 'Music only'),
	('YpzV6h6xiZI', 'League of Legends : Urf Rap', 'No captions'),
	('Bl4X8bCVnQU', 'Dunkey''s 1 Million Subs Dance Hoedown', 'Music only'),
	('EX9aDLjKYww', 'Relaxing Space Safari', 'Music only'),
	('YgSSql6MAKo', 'Dunkey Dance', 'Music only'),
	('6n83K-cHHg4', 'Youtubers', 'Just noises'),
	('pKYeAN-_wFI', 'Whiplash and La La Land', 'No captions'),
	('waXb8QGdEYQ', 'Dunkey and Leah''s Wedding', 'No captions (mostly music)'),
	('aaLiLRVeaZA', 'Metal Gear Solid Explained', 'No captions'),
	('n0qIgPIDy00', 'funny birds have a sword fight with their beaks ROFL', 'Music only'),
	('fXSjsSHWekw', 'Maneater', 'No captions'),
	('dW0QCU3RPtY', 'Worms', 'No captions'),
	('XZp6zxh2yjE', 'The Sopranos for PS2', 'No captions'),
	('iGOMViJlQmE', 'Reacting to the FAKEST GAMER EVER !?', 'No captions'),
	('TVVum6X3TuM', 'More Dunkey More Problems', 'No captions'),
	('iTBW6jbHgX0', 'Playtime', 'No captions'),
	('ajh9e3PDAOc', 'Battlefield 2077', 'Music and noises only'),
	('KuvDsT4sRzU', 'Donkey Kong December', 'No captions'),
	('DRnMwtdegII', 'Super Donkey Kong Shake', 'No captions'),
	('wXqHtF4I3M8', '100 Movie Recommendations in One Minute', 'No audio'),
	('o2TdptvwVKQ', 'Franken RPG', 'No captions'),
	('IiMJzjKKtgg', 'Dunkey''s Epic 30k Dunder Dance Down', 'Music only'),
	('RDcWc1t9XN8', 'League of Legends : Bouncy Time', 'No captions'),
	('mGLMi9kXTRI', 'The Next Smash Bros Roster', 'No captions');